# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='title',
            field=models.TextField(max_length=50),
        ),
    ]
