# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0002_auto_20170720_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='executed',
            field=models.BooleanField(default=False),
        ),
    ]
