# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_auto_20170715_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
