# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 19:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0003_auto_20170715_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='todo_created_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
