# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 21:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0005_remove_note_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='author',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='auth.User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='note',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
