# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 21:11
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0006_auto_20170713_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='author',
            field=models.TextField(verbose_name=django.contrib.auth.models.User),
        ),
    ]
